routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('/home' , 'Admin\HomeController');

//route header
Route::get('/' , 'HomeController@index');
Route::get('/books' , 'BookController@index');
Route::get('/articles' , 'ArticleController@index');
Route::get('/courses' , 'CourseController@index');
Route::get('/episodes' , 'EpisodeController@index');
Route::get('/story' , 'StoryController@index');
Route::get('/games' , 'GameController@index');
Route::post('/comment' , 'HomeController@comment');
Route::post('/discuss' , 'HomeController@discuss');

Route::get('/articles/{articleSlug}' , 'ArticleController@single');
Route::get('/books/{bookSlug}' , 'BookController@single');
Route::get('/courses/{courseSlug}' , 'CourseController@single');
Route::get('/stories/{courseSlug}' , 'StoryController@single');



//register email
//Route::get('/user/active/email/{token}' , 'UserController@activation')->name('activation.account');

//login google
Route::get('login/google', 'Auth\LoginController@redirectToProvider');
Route::get('login/google/callback', 'Auth\LoginController@handleProviderCallback');


//namespace('Admin')->prefix('admin')

Route::group(['namespace'=>'Admin' ,'middleware'=>['auth:web'], 'prefix'=>'admin'] ,function(){
    Route::get('/panel','PanelController@index');
    Route::post('/panel/upload-image','PanelController@uploadImageSubject');

    Route::resource('articles', 'ArticleController');
    Route::resource('books', 'BookController');
    Route::resource('courses', 'CourseController');
    Route::resource('stories', 'StoryController');
    Route::resource('games', 'GameController');
    Route::get('/comments/unsuccessful' , 'CommentController@unsuccessful');
    Route::resource('comments', 'CommentController');
    Route::resource('episodes', 'EpisodeController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');


    Route::group(['prefix'=>'users'], function (){
        Route::get('/' , 'UserController@index');
        Route::resource('level' ,'LevelManageController' , ['parameters'=>['level'=>'user '] ]);
        Route::delete('/{user}/destroy' , 'UserController@destroy')->name('users.destroy');
    });
});



Route::group(['namespace' => 'Auth'] , function (){
    // Authentication Routes...
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login')->name('login');
    Route::get('logout', 'LoginController@logout')->name('logout');

    //   login by google
    Route::get('login/google', 'LoginController@redirectToProvider');
    Route::get('login/google/callback', 'LoginController@handleProviderCallback');

    // Registration Routes...
    Route::get('register', 'RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'ResetPasswordController@reset')->name('password.update');
});

app/Story.php
<?php

namespace App;

use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;

class Story extends Model
{
    use Sluggable;

    protected $guarded = [];

    protected $casts = [
        'images' => 'array'
    ];
    /**
     * @var mixed
     */

    /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'title'
            ]
        ];
    }

    public function path()
    {
//        $locale = app()->getLocale();
        return "/stories/$this->slug";
    }

    /**
     * Get all of the post's comments.
     */
    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/Admin/StoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Story;
use App\Http\Requests\StoryRequest;
use Illuminate\Http\Request;

class StoryController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stories = Story::latest()->paginate(20);
        return view('Admin.stories.all' , compact('stories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.stories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoryRequest|Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoryRequest $request)
    {
        $imagesUrl = $this->uploadImages($request->file('images'));
        auth()->user()->story()->create(array_merge($request->all() , [ 'images' => $imagesUrl]));

        return redirect(route('stories.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Story  $story
     * @return \Illuminate\Http\Response
     */
    public function show(Story $story)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Story  $story
     * @return \Illuminate\Http\Response
     */
    public function edit(Story $story)
    {
        return view('Admin.stories.edit' , compact('story'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param StoryRequest|Request $request
     * @param  \App\Story $story
     * @return \Illuminate\Http\Response
     */
    public function update(StoryRequest $request, Story $story)
    {
        $file = $request->file('images');
        $inputs = $request->all();

        if($file) {
            $inputs['images'] = $this->uploadImages($request->file('images'));
        } else {
            $inputs['images'] = $story->images;
            $inputs['images']['thumb'] = $inputs['imagesThumb'];

        }

        unset($inputs['imagesThumb']);
        $story->update($inputs);

        return redirect(route('stories.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Story  $story
     * @return \Illuminate\Http\Response
     */
    public function destroy(Story $story)
    {
        $story->delete();
        return redirect(route('stories.index'));
    }
}

app/Http/Controllers/StoryController.php
<?php

namespace App\Http\Controllers;

use App\Story;
use Carbon\Carbon;
use Illuminate\Http\Request;

class StoryController extends Controller
{
    public function index(Story $story)
    {
        $story->increment('viewCount');
        if(cache()->has('storys')) {
            $storys = cache('storys');
        } else {
            $storys = Story::latest()->take(8)->get();
            cache(['storys' => $storys] , Carbon::now()->addMinutes(10));
        }
        return view('stories' , compact('storys'));
    }

    public function single(Story $story)
    {
        $story->increment('viewCount');
        $comments = $story->comments()->where('approved' , 1)
            ->where('parent_id' , 0)->latest()->get();

//        $storys = Story::whereTitle('داستان نویسی')->get();
//        dd($storys);
        return view('Home.articles' , compact('story' ,'comments' ));
    }
}

resources/views/Admin/stories/all.blade.php
@extends('Admin.master')

@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header head-section">
            <h2>داستان ها</h2>
            <a href="{{ route('stories.create') }}" class="btn btn-sm btn-primary">ارسال داستان</a>
        </div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered">
                <thead>
                <tr>
                    <th>عنوان داستان</th>
                    <th>تعداد نظرات</th>
                    <th>مقدار بازدید</th>
                    <th>تنظیمات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($stories as $story)
                    <tr>
                        <td><a href="{{ $story->path() }}">{{ $story->title }}</a></td>
                        <td>{{ $story->commentCount }}</td>
                        <td>{{ $story->viewCount }}</td>
                        <td>
                            <form action="{{ route('stories.destroy'  , $story->id) }}" method="post">
                                {{ method_field('delete') }}
                                {{ csrf_field() }}
                                <div class="btn-group btn-group-xs">
                                    <a href="{{ route('stories.edit' , $story->id) }}"  class="btn btn-primary">ویرایش</a>
                                    <button type="submit" class="btn btn-danger">حذف</button>
                                </div>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <div style="text-align: center">
            {!! $stories->render() !!}
        </div>
    </div>
@endsection

resources/views/Admin/stories/create.blade.php
@extends('Admin.master')

@section('script')
    <script src="/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('body' ,{
            filebrowserUploadUrl : '/admin/panel/upload-image',
            filebrowserImageUploadUrl :  '/admin/panel/upload-image'
        });
    </script>
@endsection

@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header head-section">
            <h2>ایجاد داستان</h2>
        </div>
        <form class="form-horizontal" action="{{ route('stories.store') }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            @include('Admin.section.errors')
            <div class="form-group">
                <div class="col-sm-12">
                    <label for="title" class="control-label">عنوان داستان</label>
                    <input type="text" class="form-control" name="title" id="title" placeholder="عنوان را وارد کنید" value="{{ old('title') }}">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label for="title" class="control-label">زبان داستان</label>
                    <select name="lang" id="lang" class="form-control">
                        <option value="fa" selected>فارسی</option>
                        <option value="en">انگلیسی</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label for="description" class="control-label">توضیحات کوتاه</label>
                    <textarea rows="5" class="form-control" name="description" id="description" placeholder="توضیحات را وارد کنید">{{ old('description') }}</textarea>
                </div>
            </div>
            <div class="form-group">
              <div class="col-sm-12">
                  <label for="body" class="control-label">متن</label>
                  <textarea rows="5" class="form-control" name="body" id="body" placeholder="متن داستان را وارد کنید">{{ old('body') }}</textarea>
              </div>
            </div>
            <div class="form-group">
                <div class="col-sm-6">
                    <label for="images" class="control-label">تصویر داستان</label>
                    <input type="file" class="form-control" name="images" id="images" placeholder="تصویر داستان را وارد کنید">
                </div>
                <div class="col-sm-6">
                    <label for="tags" class="control-label">تگ ها</label>
                    <input type="text" class="form-control" name="tags" id="tags" placeholder="تگ ها را وارد کنید" value="{{ old('tags') }}">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-danger">ارسال</button>
                </div>
            </div>
        </form>
    </div>
@endsection

resources/views/Admin/stories/edit.blade.php
@extends('Admin.master')
@section('script')
    <script src="/ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace('body' ,{
            filebrowserUploadUrl : '/admin/panel/upload-image',
            filebrowserImageUploadUrl :  '/admin/panel/upload-image'
        });
    </script>
@endsection
@section('content')
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <div class="page-header head-section">
            <h2>ویرایش داستان</h2>
        </div>
        <form class="form-horizontal" action="{{ route('stories.update' , $story->id) }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}

            @include('Admin.section.errors')
            <div class="form-group">
                <div class="col-sm-12">
                    <label for="title" class="control-label">عنوان داستان</label>
                    <input type="text" class="form-control" name="title" id="title" placeholder="عنوان را وارد کنید" value="{{ $story->title }}">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label for="title" class="control-label">زبان داستان</label>
                    <select name="lang" id="lang" class="form-control">
                        <option value="fa" {{ $story->lang == 'fa' ? 'selected' : '' }}>فارسی</option>
                        <option value="en" {{ $story->lang == 'en' ? 'selected' : '' }}>انگلیسی</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label for="description" class="control-label">توضیحات کوتاه</label>
                    <textarea rows="5" class="form-control" name="description" id="description" placeholder="توضیحات را وارد کنید">{{ $story->description }}</textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label for="body" class="control-label">متن</label>
                    <textarea rows="5" class="form-control" name="body" id="body" placeholder="متن داستان را وارد کنید">{{ $story->body }}</textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <label for="images" class="control-label">تصویر داستان</label>
                    <input type="file" class="form-control" name="images" id="images" placeholder="تصویر داستان را وارد کنید">
                </div>
                <div class="col-sm-12">
                    <div class="row">
                        @foreach( $story->images['images'] as $key => $image)
                            <div class="col-sm-2">
                                <label class="control-label">
                                    {{ $key }}
                                    <input type="radio" name="imagesThumb" value="{{ $image }}" {{ $story->images['thumb'] == $image ? 'checked' : '' }} />
                                    <a href="{{ $image }}" target="_blank"><img src="{{ $image }}" width="100%"></a>
                                </label>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-6">
                    <label for="tags" class="control-label">تگ ها</label>
                    <input type="text" class="form-control" name="tags" id="tags" placeholder="تگ ها را وارد کنید" value="{{ $story->tags  }}">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-danger">ویرایش</button>
                </div>
            </div>
        </form>
    </div>
@endsection